### ISSUE TITLE
Chapter Advisor Position

### ISSUE THREAD

**Issue by DLance96** [beta-nu-theta-chi/ox-dashboard#16]
Add a way for our chapter advisor to view everything that the President can view (aka Dan Neuman)

**Comment by matthewbentley** [comment]
I think the best way to do this will be to allow multiple people to hold one position.  That way we can also add the VP adviser as VP, treasurer adviser as treasurer, etc.

That should only require changing up the verify_position decorator.

**Comment by kihashi** [comment]
As a chapter advisor, I would argue that unless there's a compelling reason
otherwise, we should have access to everything. I may be the secretary
advisor, but most of us are past presidents. We might be able to advise
other positions if we have the information.

Love and Respect,
John Cleaver

**Comment by matthewbentley** [comment]
In #18, the 'Adviser' position now can access everything the president can.  However, we might have to look through the bylaws to make sure there's nothing exposed that is confidential to, for example, the president and scholarship chair.

This change will allow multiple people to hold the 'Adviser' position (as well as any other).

**Comment by DLance96** [comment]
All that seems fine to me having glanced over the current iteration of the bylaws
