### ISSUE TITLE
Emergency Phone Tree

### ISSUE THREAD

**Issue by jcassarly** [beta-nu-theta-chi/ox-dashboard#45]
- Could generate some plantuml or something like that to make the output look like a tree

**Comment by kihashi** [comment]
Mermaid is what gitlab uses. It's popular in the JavaScript world.

**Comment by jcassarly** [comment]
Ah you right, forgot about that. I mostly use PlantUML at work and forgot that mermaid existed

**Comment by jcassarly** [comment]
This should have a button to generate the emergency phone tree (overwriting any previously existing one if it exists) where it assigns the president the 7 other members of EC, then all the other non-marshal members get the active roster divided evenly between them and the Marshal gets all of the candidates

**Comment by jcassarly** [comment]
After discussion with Jerry, having a graphical display with mermaid or plantuml is unnecessary

instead there should be 2 ways to see the data in the tree
1. A table with each brother and their assignees
2. On the brother page, the person above and people below are listed
