### ISSUE TITLE
Automatically set up for a new semester

### ISSUE THREAD

**Issue by helper08** [beta-nu-theta-chi/ox-dashboard#58]
Add a button that does the following
- Delete all old meet a brothers (depends on #59)
- Delete all old events from the last semester
    - Chapter
    - Committee Meetings
    - Philanthropy Events
    - Scholarship Events
    - Recruitment Events
    - Service Events
- Delete all Excuses
    - Deleting the events should remove the old ones
- Create all semesters that do not exists in the current year range of semesters
- Create a chapter event every Sunday until the end of the semester

**Comment by oxdashboard-svc** [comment]
Probably want to add a form on the presidents page instead of just a button to choose the semester you want to delete events before (makes the code a bit simpler and probably gives whoever is clicking the button more confidence they didnt just break everything)
