### ISSUE TITLE
Meet-a-Brother Scheduler

### ISSUE THREAD

**Issue by jcassarly** [beta-nu-theta-chi/ox-dashboard#59]
a spreadsheet/schedule/table that the Marshal can edit that everyone can see to keep track of MABs. If possible, with a feature for people to indicate if they have completed the meeting that the Marshal can see

**Comment by jcassarly** [comment]
- need a way to mark whether a candidate already knows a person well enough that they do not need to do a meet a brother with them
    - could have this be a check box in the spreadsheet

May need to put the different parts of the marshal UI on separate pages sot hat we dont have multiple forms you can edit at once

## UI

### Spreadsheet in Marshal View
Top of the page has a spreadsheet like 
![image](https://user-images.githubusercontent.com/22135705/95025738-fcea4680-0659-11eb-89a9-81ce93079307.png)

except the numbers are checkboxes and can be unchecked

All changes needs to be updated with a submit button

redirects to marshal page on submission

### MAB Selector in Marshal View
When this page is open, an uneditable version of the spreadsheet is visible

Each candidate should be listed in a table under the aforementioned spreadsheet with two meet a brother fields that are dropdowns listing the brothers that they have not met with based on the above spreadsheet (thats been submitted)

Should probably not allow the same brother to be assigned to a single candidate twice in one week

Above all the candidates there should be a randomize button that when pressed will reload the page with randomly selected brothers (does not submit - probably need to note that)
- Additionally, there should be checkboxes next to the candidates that control whether the candidates get randomly assigned MABs or not
    - these checkboxes should be checked by default
    - if the checkbox if unchecked and brothers are set, clicking the randomize button will not assign a brother that is assigned to these candidates and it will use the selected brother
    - randomization should not assign the same brother to a candidate twice

There should be a no brother option the marshal can select to allow the marshal to choose not to assign a brother to the candidate.  this is automatically selected if the candidate runs out of brothers to meet with

redirects to below page on submission

### A view that shows this weeks Meet a Brothers in a table
- Lives under General Info
- Should be a table listing each candidate along with the their Meet a Brother (showing contact info (phone and email, maybe discord) and an unedittable checkbox that says whether the MAB has happened)
- The submission of the selector page will redirect to this page
- There should be multiple tables for each week each in their own panel
    - these tables should be shown latest first
    - Start at latest, find weeks until the beginning of the semester

Table:
|Candidate Name|Case ID|Discord|Brother Name|Case ID|Discord|Completed Checkbox|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|first last|abc123|user#number|first last|abc123|user#number|uneditable checkbox|
||||first last|abc123|user#number|uneditable checkbox|

### Brother page view
- Shows the brother which candidates the have been assigned to them

|Candidate Name|Phone Number|Email|Discord|MAB Completed?|Complete MAB|
|:--:|:--:|:--:|:--:|:--:|:--:|
|first last|###-###-####|abc123@case.edu|user#number|uneditable checkbox|button that will cause the checkbox to become checked when clicked|

Candidates will see the same view as brothers except that `Candidate Name` Will be replaced with `Brother Name`

Whenever either the candidate or the brother clicks the complete button, this change should be reflected on both pages along with the main viewer under general info

## MAB

MAB(candidate_id: foreign key to `Brother`, brother_id: foreign key to `Brother`, completed: boolean, week: date)

- candidate id is the foreign key of the Brother that represents the candidate in the MAB relation
- brother id is the foreign key of the Brother that represents the brother in the MAB relation
- completed states whether the meeting has been completed
- week is a date that is assigned on creation for when the MAB is supposed to happen
    - this will be used my the general info page to filter the MABs for the latest week

**Comment by helper08** [comment]
This is done with the exception of the "Marshal Removal of Brothers for MAB possibilities feature.
