### ISSUE TITLE
[Bug] Phone number entry does not display improper formatting correctly

### ISSUE THREAD

**Issue by jcassarly** [beta-nu-theta-chi/ox-dashboard#64]
If a user enters a phone  number in the wrong format, it takes you back to the editting page, but does not display an error message

For example

(555)-555-5555 wiill not work and not reasonable error message is displayed.

1. The regex should maybe allow this pattern
2. a proper error message should be displayed if the regex does not match

**Comment by kihashi** [comment]
In my experience, you're better off not validating the format of a phone number at all. There are a lot of corner cases, especially if you include international numbers.

**Comment by jcassarly** [comment]
Seems fair, the regex was already there, so I didn't really see a reason to remove it.  Thats probably a much easier solution too.

**Comment by helper08** [comment]
This should have been resolved when I restored error messages for forms in the templates. The regex allows for up to 15 digits so international numbers should be okay. This leaves only the issue that you cannot include dashes in the phone number. I guess we can determine if that's a big enough deal that we should rewrite the validator? Honestly, as long as the error message is explicit enough that you have to only include integers I think it's fine.

**Comment by jcassarly** [comment]
I agree, go ahead and close this issue then
