### ISSUE TITLE
Assigning the same meet a brother twice can cause an integrity constraint failure

### ISSUE THREAD

**Issue by jcassarly** [beta-nu-theta-chi/ox-dashboard#75]
I was messing around with adding some meet a brothers and added a single brother.  When I went to assign meet a brothers, I was able to click the drop down menus to assign the same brother to a candidate twice:

![image](https://user-images.githubusercontent.com/22135705/103487212-c09dc200-4dd1-11eb-9bd7-91df04b54a60.png)

Once I submit, I get an integrity error because meet a brothers need to be unique.  I think we need some error checking on the meet a brother creation page to yell at the user if they try to create a MAB that already exists and prevent them from doing so. 

![image](https://user-images.githubusercontent.com/22135705/103487259-11adb600-4dd2-11eb-8cb2-87c78c3af101.png)

**Comment by jcassarly** [comment]
Also, Im not sure the meet a brother page has a check to verify the brother is logged in.  We should fix that because that has contact info about brothers.  I would prefer only brothers have access to that information

**Comment by helper08** [comment]
Both of these issues should be fixed now
